
import { Question, GiftDefinition } from './types';

export const ALL_QUESTIONS: Question[] = [
  { id: 1, text: '1. Fácil de delegar una responsabilidad importante a los demás.' },
  { id: 2, text: '2. Percibo claramente la diferencia entre la verdad y el error.' },
  { id: 3, text: '3. Llevo a otros a una decisión para la salvación por la fe en Cristo.' },
  { id: 4, text: '4. Verbalmente animo a los vacilantes, preocupados o desanimados.' },
  { id: 5, text: '5. Creo que Dios mantendrá sus promesas a pesar de las evidencias circunstanciales.' },
  { id: 6, text: '6. Manejo bien el dinero a fin de dar generosamente para la obra del Señor.' },
  { id: 7, text: '7. En el nombre del Señor, curo enfermedades.' },
  { id: 8, text: '8. Ayudo a los líderes principales a aliviarlos en su tarea esencial.' },
  { id: 9, text: '9. Proveo alimento/alojamiento amablemente a las personas necesitadas.' },
  { id: 10, text: '10. Al orar por los demás, a menudo pierdo la noción del tiempo.' },
  { id: 11, text: '11. Tengo la habilidad para descubrir nuevas verdades para mí mismo.' },
  { id: 12, text: '12. Persuado a otros para avanzar hacia el logro de los objetivos bíblicos.' },
  { id: 13, text: '13. Trabajo alegremente con personas ignoradas por la mayoría.' },
  { id: 14, text: '14. Me adapto fácilmente a una cultura diferente de la mía.' },
  { id: 15, text: '15. Disfruto de la responsabilidad por el crecimiento espiritual de un grupo de cristianos.' },
  { id: 16, text: '16. Disfruto el ser llamado a hacer trabajos especiales en torno de la iglesia.' },
  { id: 17, text: '17. Facilito a las personas para que aprendan las verdades bíblicas en detalle.' },
  { id: 18, text: '18. Aplico la verdad en forma efectiva en mi propia vida.' },
  { id: 19, text: '19. Puedo organizar ideas, personas, cosas y el tiempo para un ministerio más efectivo.' },
  { id: 20, text: '20. Juzgo bien lo que es malo y lo que es bueno (o mal o bien).' },
  { id: 21, text: '21. Comparto con alegría cómo Cristo me ha atraído a Él.' },
  { id: 22, text: '22. Soy un instrumento para desplazar a los complacientes y reorientar a los descarriados para hacer frente a la realidad espiritual.' },
  { id: 23, text: '23. Generalmente me entusiasmo más con el futuro que con el pasado.' },
  { id: 24, text: '24. Doy cosas o dinero generosamente para la obra del Señor.' },
  { id: 25, text: '25. En el nombre del Señor, curo las alteraciones emocionales.' },
  { id: 26, text: '26. Acomodo o limpio las instalaciones relacionadas con la iglesia.' },
  { id: 27, text: '27. Facilito un buen refugio para los huéspedes.' },
  { id: 28, text: '28. Tengo la impresión que tomo los pedidos de oración más en serio que otros cristianos.' },
  { id: 29, text: '29. Dispongo de conocimientos de la verdad que traen convicción a los demás cristianos.' },
  { id: 30, text: '30. Sé a dónde estoy yendo y veo que otros cristianos me sigan.' },
  { id: 31, text: '31. Ayudo a los indignos.' },
  { id: 32, text: '32. Aprendo otro idioma con el fin de servir a un pueblo diferente.' },
  { id: 33, text: '33. Me sacrifico por los jóvenes o descarriados cristianos.' },
  { id: 34, text: '34. Disfruto de los trabajos de rutina de la iglesia que podría aburrir a otros.' },
  { id: 35, text: '35. Explico claramente la enseñanza de las Escrituras a los demás.' },
  { id: 36, text: '36. Disfruto elaborando soluciones a problemas complicados.' },
  { id: 37, text: '37. Soy capaz de establecer objetivos y hacer planes eficaces para llegar a ellos.' },
  { id: 38, text: '38. Tiendo a mirar por debajo de la superficie y cuestiono los motivos de las personas.' },
  { id: 39, text: '39. Explico claramente las verdades bíblicas e indico a la gente a Jesús como el Salvador.' },
  { id: 40, text: '40. Desafío verbalmente a aquellos que parecen espiritualmente apáticos.' },
  { id: 41, text: '41. Confío en la presencia y poder de Dios en lo imposible.' },
  { id: 42, text: '42. Me siento profundamente conmovido cuando me enfrento con necesidades financieras urgentes en la obra de Dios.' },
  { id: 43, text: '43. En el nombre del Señor, trato con éxito a aquellos que están espiritualmente enfermos.' },
  { id: 44, text: '44. Digito, archivo o registro datos o minutas para la obra del Señor.' },
  { id: 45, text: '45. Tengo la habilidad de hacer que los extranjeros se sientan en casa.' },
  { id: 46, text: '46. La oración es uno de mis ejercicios espirituales favoritos.' },
  { id: 47, text: '47. Adquiero y domino los datos y principios de la verdad bíblica.' },
  { id: 48, text: '48. Influyo en otros para el logro de los objetivos de la Biblia.' },
  { id: 49, text: '49. Visito hospitales u hogares de jubilados y soy bendecido.' },
  { id: 50, text: '50. Puedo relacionarme bien con los cristianos de diferentes razas, idiomas o culturas.' },
  { id: 51, text: '51. Conozco íntimamente y soy bien conocido por aquellos a quienes sirvo y guío.' },
  { id: 52, text: '52. Siento satisfacción en hacer las tareas domésticas para la gloria de Dios.' },
  { id: 53, text: '53. Se me hace difícil hacer comprender las verdades bíblicas a los demás.' },
  { id: 54, text: '54. De varias alternativas bíblicas, elijo una opción, que por lo general funciona.' },
  { id: 55, text: '55. Puedo liderar un grupo cuando hacen decisiones en conjunto.' },
  { id: 56, text: '56. Reconozco exactamente qué dones espirituales otros cristianos tienen y no tienen.' },
  { id: 57, text: '57. Enfatizo un mensaje, el cual es ante todo el Evangelio de salvación.' },
  { id: 58, text: '58. Puedo aconsejar eficazmente al confuso, culpable o adicto.' },
  { id: 59, text: '59. Me siento seguro de conocer la voluntad especial de Dios para el futuro crecimiento de su obra aún cuando otros no lo sienten.' },
  { id: 60, text: '60. Soy capaz de ganar mucho dinero para dar para la obra del Señor.' },
  { id: 61, text: '61. Oro por otros para que se produzca la curación.' },
  { id: 62, text: '62. Distribuyo literatura evangélica y otros impresos en mi comunidad.' },
  { id: 63, text: '63. Tengo una gentileza real y apreciación por las visitas.' },
  { id: 64, text: '64. Dios siempre responde a mis oraciones de una manera tangible.' },
  { id: 65, text: '65. Estudio y leo mucho para aprender las verdades bíblicas.' },
  { id: 66, text: '66. Guío a otros a través de las dificultades en la obra del Señor.' },
  { id: 67, text: '67. Llevo a los confinados a dar una vuelta y los atiendo de maneras prácticas.' },
  { id: 68, text: '68. Disfruto de la vida en un país extranjero.' },
  { id: 69, text: '69. Ayudo a los necesitados cristianos guiándolos por las partes importantes de la Biblia y orando con ellos.' },
  { id: 70, text: '70. Estoy dispuesto a tomar las órdenes, mejor que darlas.' },
  { id: 71, text: '71. Comunico las verdades bíblicas a otros, lo que produce cambios en el conocimiento, actitudes, valores o conductas.' },
  { id: 72, text: '72. Cuando designo a otros para las diferentes posiciones, demuestran ser buenas selecciones.' },
  { id: 73, text: '73. Puedo reclutar cristianos y ponerlos a trabajar para que ejerciten sus dones espirituales.' },
  { id: 74, text: '74. Puedo ver al farsante antes que su falsedad sea claramente evidente.' },
  { id: 75, text: '75. Ando buscando continuamente a los no creyentes, a fin de ganarlos para el Señor.' },
  { id: 76, text: '76. Consuelo a los cristianos en su aflicción o sufrimiento.' },
  { id: 77, text: '77. Confío en la fiabilidad de Dios cuando todo parece oscuro.' },
  { id: 78, text: '78. Estoy dispuesto a mantenerme en el nivel más bajo de vida a fin de beneficiar la obra de Dios.' },
  { id: 79, text: '79. Ayudo efectivamente a aquellos que son débiles mentales.' },
  { id: 80, text: '80. Soy feliz de ser un ayudante del profesor en una clase bíblica.' },
  { id: 81, text: '81. Disfruto con personas extranjeras en mi casa.' },
  { id: 82, text: '82. Algunas veces oro cuando probablemente debería estar haciendo otras cosas.' }, // This question seems to appear twice in the OCR for page 5. Using the first instance as Q82. The second instance is identical.
  { id: 83, text: '83. Puedo distinguir puntos de referencias y hechos importantes de las Escrituras.' },
  { id: 84, text: '84. Otros me siguen porque tengo conocimiento que contribuye a la edificación de mi iglesia.' },
  { id: 85, text: '85. Hablo alegremente con las personas que están en prisión o confinadas.' },
  { id: 86, text: '86. Tengo capacidad para aprender idiomas extranjeros.' },
  { id: 87, text: '87. Puedo restaurar a las personas que se han desviado de su comunidad cristiana.' },
  { id: 88, text: '88. Disfruto cuando otros expresan que necesitan ayuda.' },
  { id: 89, text: '89. Instruyo a los cristianos para que sean discípulos más obedientes de Cristo.' },
  { id: 90, text: '90. Siento la presencia única de Dios cuando se necesita hacer decisiones importantes.' }
];

export const GIFTS_DEFINITIONS: GiftDefinition[] = [
  { id: 'A', name: 'Administración', questions: [1, 19, 37, 55, 73], description: 'El don de la administración es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para comprender claramente los objetivos inmediatos y a largo alcance de una unidad particular del cuerpo de Cristo y para diseñar y ejecutar planes efectivos para el cumplimiento de las metas. (1 Corintios 12:28; Hechos 6:1-7; Hechos 27:11; Lucas 14:28-30; Tito 1:5)' },
  { id: 'B', name: 'Discernimiento', questions: [2, 20, 38, 56, 74], description: 'El don de discernimiento de espíritus es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para que conozcan con certeza si ciertos comportamientos pretenden ser de Dios, si son realmente divinas, humanas o satánicas. (1 Corintios 12:10; Hechos 5:1-11; Hechos 16:16-18; 1 Juan 4:1-6; Mateo 16:21-23)' },
  { id: 'C', name: 'Evangelista', questions: [3, 21, 39, 57, 75], description: 'El don de evangelista es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo de compartir el evangelio con los no creyentes de tal manera que los hombres y las mujeres lleguen a ser discípulos de Jesús y miembros responsables del cuerpo de Cristo. (Efesios 4:11-14; 2 Timoteo 4:5; Hechos 8:5,6; Hechos 8:26-40; Hechos 14:21; Hechos 21:8)' },
  { id: 'D', name: 'Exhortación', questions: [4, 22, 40, 58, 76], description: 'El don de exhortación es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para expresar palabras de consuelo, consolación, incentivo y consejo a otros miembros del cuerpo, de tal manera que ellos se sientan ayudados y sanados. (Romanos 12:8; 1 Timoteo 4:13; Hebreos 10:25; Hechos 14:22)' },
  { id: 'E', name: 'Fe', questions: [5, 23, 41, 59, 77], description: 'El don de la fe es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para discernir con extraordinaria confianza la voluntad y propósitos de Dios para su obra. (1 Corintios 12:9; Hechos 11:22-24; Hechos 27:21-25; Hebreos 11; Romanos 4:18-21)' },
  { id: 'F', name: 'Contribución', questions: [6, 24, 42, 60, 78], description: 'El don de contribuir es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para contribuir con sus recursos materiales para la obra del Señor con liberalidad y alegría. (Romanos 12:8; 1 Corintios 8:1-7; 2 Corintios 9:2-8; Marcos 12:41-44)' },
  { id: 'G', name: 'Curación', questions: [7, 25, 43, 61, 79], description: 'El don de curación es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para servir como un intermediario humano a través del cual Dios se complace curar las enfermedades y restaurar la salud, aparte del uso de medios naturales. (1 Corintios 12:9, 28; Hechos 3:1-10; Hechos 5:12-16; Hechos 9:32-35; Hechos 28:7-10)' },
  { id: 'H', name: 'Ayuda', questions: [8, 26, 44, 62, 80], description: 'El don de ayuda es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para invertir los talentos que ellos tienen en el cuerpo, lo que permite a otros, aumentar la eficacia de sus propios dones espirituales. (1 Corintios 12:28; Romanos 16:1,2; Hechos 9:36; Lucas 8:2,3; Marcos 15:40, 41)' },
  { id: 'I', name: 'Hospitalidad', questions: [9, 27, 45, 63, 81], description: 'El don de hospitalidad es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para proveer una casa abierta y una cordial bienvenida a aquellos necesitados de alimento y hospedaje. (1 Pedro 4:9; Romanos 12:9-13; Romanos 16:23; Hechos 6:14, 15; Hebreos 13:1, 2)' },
  { id: 'J', name: 'Intercesión', questions: [10, 28, 46, 64, 82], description: 'El don de intercesión es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para orar por largos períodos de tiempo sobre una base regular y ver las respuestas frecuentes y específicas a sus oraciones, en un grado mucho mayor que lo que se espera del cristiano común. (Santiago 5:14-16; 1 Timoteo 2:1, 2; Colosenses 1:9-12; Colosenses 4:12, 13; Hechos 12:12; Lucas 22:41-44)' },
  { id: 'K', name: 'Conocimiento', questions: [11, 29, 47, 65, 83], description: 'El don del conocimiento es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para descubrir, acumular, analizar y aclarar información e ideas que son aplicables para el crecimiento y bienestar del cuerpo. (1 Corintios 2:14; 1 Corintios 12:8; Hechos 5:1-11; Colosenses 2:2, 3; 2 Corintios 11:6)' },
  { id: 'L', name: 'Liderazgo', questions: [12, 30, 48, 66, 84], description: 'El don del liderazgo es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para establecer metas de acuerdo con el propósito de Dios para el futuro y para comunicar esas metas a los demás, de tal manera que ellos de forma voluntaria y armoniosa trabajen juntos para lograr esas metas para la gloria de Dios. (1 Timoteo 5:17; Hechos 7:10; Hechos 15:7-11; Romanos 12:8; Hebreos 13:17; Lucas 9:51)' },
  { id: 'M', name: 'Misericordia', questions: [13, 31, 49, 67, 85], description: 'El don de misericordia es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para sentir una empatía y compasión genuina por las personas (tanto cristianas como no cristianas) que sufren de problemas físicos, mentales o emocionales preocupantes y traducir esa compasión en hechos de alegría que reflejen el amor de Cristo y alivien el sufrimiento. (Romanos 12:8; Marcos 9:41; Hechos 16:33-34; Lucas 10:33-35; Marcos 20:29-34; Marcos 25:34-40; Hechos 11:28-30)' },
  { id: 'N', name: 'Misionero', questions: [14, 32, 50, 68, 86], description: 'El don misionero es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para ministrar cualquier otro don espiritual que ellos tienen en una segunda cultura. (1 Corintios 9:19-23; Hechos 8:4; Hechos 13:2, 3; Hechos 22:21; Romanos 10:15)' },
  { id: 'O', name: 'Pastor', questions: [15, 33, 51, 69, 87], description: 'El don de pastor es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para asumir una responsabilidad personal a largo plazo por el bienestar espiritual de un grupo de creyentes. (Efesios 4:11-14; 1 Timoteo 3:1-7; Juan 10:1-18; 1 Pedro 5:1-3)' },
  { id: 'P', name: 'Servicio', questions: [16, 34, 52, 70, 88], description: 'El don del servicio es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para identificar las necesidades no satisfechas involucradas en una tarea relacionada con la obra de Dios y para hacer uso de los recursos disponibles para satisfacer esas necesidades y ayudar a alcanzar los resultados deseados. (2 Timoteo 1:16-18; Romanos 12:7; Hechos 6:1-7; Tito 3:14; Gálatas 6:2, 10)' },
  { id: 'Q', name: 'Profesor', questions: [17, 35, 53, 71, 89], description: 'El don de enseñanza es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para comunicar información importante para la salud y el ministerio del cuerpo y sus miembros, de tal manera que otros aprendan. (1 Corintios 12:28; Efesios 4:11-14; Romanos 12:7; Hechos 18:24-28; Hechos 20:20, 21)' }, // Note: Text for "Enseñanza" from PDF, question mapping uses "Profesor" as gift name from evaluation sheet.
  { id: 'R', name: 'Sabiduría', questions: [18, 36, 54, 72, 90], description: 'El don de sabiduría es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para conocer la intención del Espíritu Santo, de tal manera que pueda recibir ideas sobre cómo el conocimiento dado, puede ser mejor aplicado a las necesidades específicas que surgen en el cuerpo de Cristo. (1 Corintios 2:1-13; 1 Corintios 12:8; Hechos 6:3, 10; Santiago 1:5-6; 2 Pedro 3:15, 16)' },
];

export const RATING_LABELS: { value: number, label: string, description: string }[] = [
    { value: 1, label: '1', description: 'Siempre Falsa / No aplica' },
    { value: 2, label: '2', description: 'Generalmente Falsa' },
    { value: 3, label: '3', description: 'Dividida entre Verdad y Falso' },
    { value: 4, label: '4', description: 'Generalmente Verdadera' },
    { value: 5, label: '5', description: 'Siempre Verdadera' },
];

export const RATING_INSTRUCTIONS = "Califique cada declaración según cómo se aplica a su vida y experiencia. Estas declaraciones han sido experimentadas satisfactoriamente en mi vida o “creo que tengo habilidad para esto”.";

export const RATING_SCALE_DESCRIPTION = 
`1: La declaración siempre es falsa o no se aplica.
2: La declaración generalmente es falsa.
3: La declaración está equitativamente dividida entre verdadero y falso.
4: La declaración generalmente es verdadera.
5: La declaración siempre es verdadera.`;

export const QUESTIONS_PER_PAGE = 10;
